/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "rbcx.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(None, None, AUTO)


PB_BIND(RegCoefs, RegCoefs, AUTO)


PB_BIND(MotorConfig, MotorConfig, AUTO)


PB_BIND(CoprocReq, CoprocReq, AUTO)


PB_BIND(CoprocReq_SetLeds, CoprocReq_SetLeds, AUTO)


PB_BIND(CoprocReq_GetButtons, CoprocReq_GetButtons, AUTO)


PB_BIND(CoprocReq_SetStupidServo, CoprocReq_SetStupidServo, AUTO)


PB_BIND(CoprocReq_UltrasoundReq, CoprocReq_UltrasoundReq, AUTO)


PB_BIND(CoprocReq_SetMotorCoupling, CoprocReq_SetMotorCoupling, AUTO)


PB_BIND(CoprocReq_MotorReq, CoprocReq_MotorReq, AUTO)


PB_BIND(CoprocReq_MotorReq_SetPosition, CoprocReq_MotorReq_SetPosition, AUTO)


PB_BIND(CoprocReq_BuzzerReq, CoprocReq_BuzzerReq, AUTO)


PB_BIND(CoprocReq_CalibratePower, CoprocReq_CalibratePower, AUTO)


PB_BIND(CoprocReq_RtcReq, CoprocReq_RtcReq, AUTO)


PB_BIND(CoprocReq_I2cReq, CoprocReq_I2cReq, AUTO)


PB_BIND(CoprocReq_OledReq, CoprocReq_OledReq, AUTO)


PB_BIND(CoprocReq_OledInit, CoprocReq_OledInit, AUTO)


PB_BIND(CoprocReq_OledDrawPixel, CoprocReq_OledDrawPixel, AUTO)


PB_BIND(CoprocReq_OledWriteString, CoprocReq_OledWriteString, AUTO)


PB_BIND(CoprocReq_OledSetCursor, CoprocReq_OledSetCursor, AUTO)


PB_BIND(CoprocReq_OledDrawLine, CoprocReq_OledDrawLine, AUTO)


PB_BIND(CoprocReq_OledDrawArc, CoprocReq_OledDrawArc, AUTO)


PB_BIND(CoprocReq_OledDrawCircle, CoprocReq_OledDrawCircle, AUTO)


PB_BIND(CoprocReq_OledDrawRectangle, CoprocReq_OledDrawRectangle, AUTO)


PB_BIND(CoprocReq_MpuReq, CoprocReq_MpuReq, AUTO)


PB_BIND(CoprocReq_EspWatchdogSettings, CoprocReq_EspWatchdogSettings, AUTO)


PB_BIND(CoprocReq_CoprocStartupMessage, CoprocReq_CoprocStartupMessage, AUTO)


PB_BIND(CoprocReq_SmartServoReq, CoprocReq_SmartServoReq, AUTO)


PB_BIND(CoprocStat, CoprocStat, AUTO)


PB_BIND(CoprocStat_ButtonsStat, CoprocStat_ButtonsStat, AUTO)


PB_BIND(CoprocStat_UltrasoundStat, CoprocStat_UltrasoundStat, AUTO)


PB_BIND(CoprocStat_MotorStat, CoprocStat_MotorStat, AUTO)


PB_BIND(CoprocStat_PowerAdcStat, CoprocStat_PowerAdcStat, AUTO)


PB_BIND(CoprocStat_VersionStat, CoprocStat_VersionStat, AUTO)


PB_BIND(CoprocStat_RtcStat, CoprocStat_RtcStat, AUTO)


PB_BIND(CoprocStat_FaultStat, CoprocStat_FaultStat, AUTO)


PB_BIND(CoprocStat_MpuStat, CoprocStat_MpuStat, AUTO)


PB_BIND(CoprocStat_MpuVector, CoprocStat_MpuVector, AUTO)


PB_BIND(CoprocStat_SmartServoStat, CoprocStat_SmartServoStat, AUTO)









