/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_RBCX_PB_H_INCLUDED
#define PB_RBCX_PB_H_INCLUDED
#include "nanopb/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _MotorMode {
    MotorMode_POWER = 0,
    MotorMode_BRAKE = 1,
    MotorMode_VELOCITY = 2,
    MotorMode_POSITION = 3,
    MotorMode_POSITION_IDLE = 4,
    MotorMode_COUPLE_POWER = 5
} MotorMode;

typedef enum _CoprocReq_LedsEnum {
    CoprocReq_LedsEnum_NONE = 0,
    CoprocReq_LedsEnum_L1 = 1,
    CoprocReq_LedsEnum_L2 = 2,
    CoprocReq_LedsEnum_L3 = 4,
    CoprocReq_LedsEnum_L4 = 8
} CoprocReq_LedsEnum;

typedef enum _CoprocReq_OledColor {
    CoprocReq_OledColor_OLED_BLACK = 0,
    CoprocReq_OledColor_OLED_WHITE = 1
} CoprocReq_OledColor;

typedef enum _CoprocReq_OledFont {
    CoprocReq_OledFont_OLED_FONT_6X8 = 0,
    CoprocReq_OledFont_OLED_FONT_7X10 = 1,
    CoprocReq_OledFont_OLED_FONT_11X18 = 2,
    CoprocReq_OledFont_OLED_FONT_16X26 = 3
} CoprocReq_OledFont;

typedef enum _CoprocStat_ButtonsEnum {
    CoprocStat_ButtonsEnum_BNONE = 0,
    CoprocStat_ButtonsEnum_BOFF = 1,
    CoprocStat_ButtonsEnum_B1 = 2,
    CoprocStat_ButtonsEnum_B2 = 4,
    CoprocStat_ButtonsEnum_B3 = 8,
    CoprocStat_ButtonsEnum_B4 = 16,
    CoprocStat_ButtonsEnum_BON = 32
} CoprocStat_ButtonsEnum;

typedef enum _CoprocStat_RtcFlags {
    CoprocStat_RtcFlags_RTC_NONE = 0,
    CoprocStat_RtcFlags_RTC_NOT_READY = 1,
    CoprocStat_RtcFlags_RTC_ALARM = 2
} CoprocStat_RtcFlags;

/* Struct definitions */
typedef struct _None {
    char dummy_field;
} None;

typedef struct _RegCoefs {
    uint32_t p;
    uint32_t i;
    uint32_t d;
} RegCoefs;

typedef struct _MotorConfig {
    uint32_t velEpsilon;
    uint32_t posEpsilon;
    uint32_t maxAccel;
} MotorConfig;

typedef struct _CoprocReq_SetLeds {
    CoprocReq_LedsEnum ledsOn;
} CoprocReq_SetLeds;

typedef struct _CoprocReq_GetButtons {
    char dummy_field;
} CoprocReq_GetButtons;

typedef struct _CoprocReq_SetStupidServo {
    uint32_t servoIndex;
    pb_size_t which_servoCmd;
    union {
        None disable;
        float setPosition;
    } servoCmd;
} CoprocReq_SetStupidServo;

typedef struct _CoprocReq_UltrasoundReq {
    uint32_t utsIndex;
    pb_size_t which_utsCmd;
    union {
        None singlePing;
    } utsCmd;
} CoprocReq_UltrasoundReq;

typedef struct _CoprocReq_SetMotorCoupling {
    uint32_t coupleAxis;
} CoprocReq_SetMotorCoupling;

typedef struct _CoprocReq_MotorReq_SetPosition {
    int32_t targetPosition;
    int32_t runningVelocity;
} CoprocReq_MotorReq_SetPosition;

typedef struct _CoprocReq_MotorReq {
    uint32_t motorIndex;
    pb_size_t which_motorCmd;
    union {
        None getState;
        int32_t setPower;
        int32_t setBrake;
        int32_t setVelocity;
        int32_t homePosition;
        CoprocReq_MotorReq_SetPosition setPosition;
        CoprocReq_MotorReq_SetPosition addPosition;
        RegCoefs setVelocityRegCoefs;
        RegCoefs setPositionRegCoefs;
        MotorConfig setConfig;
        CoprocReq_SetMotorCoupling setCoupling;
    } motorCmd;
} CoprocReq_MotorReq;

typedef struct _CoprocReq_BuzzerReq {
    bool on;
} CoprocReq_BuzzerReq;

typedef struct _CoprocReq_CalibratePower {
    uint32_t vccMv;
    uint32_t battMidMv;
    uint32_t vRef33Mv;
    uint32_t temperatureC;
} CoprocReq_CalibratePower;

typedef struct _CoprocReq_RtcReq {
    pb_size_t which_rtcCmd;
    union {
        None get;
        uint32_t setTime;
        uint32_t setAlarm;
    } rtcCmd;
} CoprocReq_RtcReq;

typedef struct _CoprocReq_OledInit {
    uint32_t height;
    uint32_t width;
    bool rotate;
    bool inverseColor;
} CoprocReq_OledInit;

typedef struct _CoprocReq_OledDrawPixel {
    uint32_t x;
    uint32_t y;
    CoprocReq_OledColor color;
} CoprocReq_OledDrawPixel;

typedef struct _CoprocReq_OledWriteString {
    char text[33];
    CoprocReq_OledFont font;
    CoprocReq_OledColor color;
} CoprocReq_OledWriteString;

typedef struct _CoprocReq_OledSetCursor {
    uint32_t x;
    uint32_t y;
} CoprocReq_OledSetCursor;

typedef struct _CoprocReq_OledDrawLine {
    uint32_t x1;
    uint32_t y1;
    uint32_t x2;
    uint32_t y2;
    CoprocReq_OledColor color;
} CoprocReq_OledDrawLine;

typedef struct _CoprocReq_OledDrawArc {
    uint32_t x;
    uint32_t y;
    uint32_t radius;
    uint32_t start_angle;
    uint32_t sweep;
    CoprocReq_OledColor color;
} CoprocReq_OledDrawArc;

typedef struct _CoprocReq_OledDrawCircle {
    uint32_t x;
    uint32_t y;
    uint32_t radius;
    CoprocReq_OledColor color;
} CoprocReq_OledDrawCircle;

typedef struct _CoprocReq_OledDrawRectangle {
    uint32_t x1;
    uint32_t y1;
    uint32_t x2;
    uint32_t y2;
    CoprocReq_OledColor color;
} CoprocReq_OledDrawRectangle;

typedef struct _CoprocReq_OledReq {
    pb_size_t which_oledCmd;
    union {
        CoprocReq_OledInit init;
        CoprocReq_OledColor fill;
        None update;
        CoprocReq_OledDrawPixel drawPixel;
        CoprocReq_OledWriteString writeString;
        CoprocReq_OledSetCursor setCursor;
        CoprocReq_OledDrawLine drawLine;
        CoprocReq_OledDrawArc drawArc;
        CoprocReq_OledDrawCircle drawCircle;
        CoprocReq_OledDrawRectangle drawRectangle;
    } oledCmd;
} CoprocReq_OledReq;

typedef struct _CoprocReq_MpuReq {
    pb_size_t which_mpuCmd;
    union {
        None init;
        None oneSend;
        None startSend;
        None stopSend;
        uint32_t setCompressCoef;
        None getCompressCoef;
    } mpuCmd;
} CoprocReq_MpuReq;

typedef struct _CoprocReq_I2cReq {
    pb_size_t which_payload;
    union {
        CoprocReq_OledReq oledReq;
        CoprocReq_MpuReq mpuReq;
    } payload;
} CoprocReq_I2cReq;

typedef struct _CoprocReq_EspWatchdogSettings {
    bool disable;
} CoprocReq_EspWatchdogSettings;

typedef struct _CoprocReq_CoprocStartupMessage {
    bool getButtons;
    bool getVersion;
    bool getRtc;
    bool has_espWatchdogSettings;
    CoprocReq_EspWatchdogSettings espWatchdogSettings;
} CoprocReq_CoprocStartupMessage;

typedef PB_BYTES_ARRAY_T(24) CoprocReq_SmartServoReq_data_t;
typedef struct _CoprocReq_SmartServoReq {
    bool expect_response;
    CoprocReq_SmartServoReq_data_t data;
} CoprocReq_SmartServoReq;

typedef struct _CoprocReq {
    pb_size_t which_payload;
    union {
        None keepalive;
        CoprocReq_SetLeds setLeds;
        CoprocReq_GetButtons getButtons;
        CoprocReq_SetStupidServo setStupidServo;
        CoprocReq_UltrasoundReq ultrasoundReq;
        CoprocReq_MotorReq motorReq;
        CoprocReq_BuzzerReq buzzerReq;
        CoprocReq_CalibratePower calibratePower;
        None shutdownPower;
        None versionReq;
        CoprocReq_RtcReq rtcReq;
        CoprocReq_I2cReq i2cReq;
        CoprocReq_EspWatchdogSettings espWatchdogSettings;
        CoprocReq_CoprocStartupMessage coprocStartupMessage;
        CoprocReq_SmartServoReq smartServoReq;
    } payload;
} CoprocReq;

typedef struct _CoprocStat_ButtonsStat {
    CoprocStat_ButtonsEnum buttonsPressed;
} CoprocStat_ButtonsStat;

typedef struct _CoprocStat_UltrasoundStat {
    uint32_t utsIndex;
    uint32_t roundtripMicrosecs;
} CoprocStat_UltrasoundStat;

typedef struct _CoprocStat_MotorStat {
    uint32_t motorIndex;
    MotorMode mode;
    int32_t power;
    int32_t velocity;
    int32_t position;
} CoprocStat_MotorStat;

typedef struct _CoprocStat_PowerAdcStat {
    uint32_t vccMv;
    uint32_t battMidMv;
    int32_t temperatureC;
} CoprocStat_PowerAdcStat;

typedef struct _CoprocStat_VersionStat {
    pb_byte_t revision[8];
    uint32_t number;
    bool dirty;
} CoprocStat_VersionStat;

typedef struct _CoprocStat_RtcStat {
    uint32_t time;
    uint32_t alarm;
    CoprocStat_RtcFlags flags;
} CoprocStat_RtcStat;

typedef struct _CoprocStat_FaultStat {
    pb_size_t which_fault;
    union {
        None oledFault;
        None mpuFault;
    } fault;
} CoprocStat_FaultStat;

typedef struct _CoprocStat_MpuVector {
    int32_t x;
    int32_t y;
    int32_t z;
} CoprocStat_MpuVector;

typedef struct _CoprocStat_MpuStat {
    uint32_t compressCoef;
    bool has_accel;
    CoprocStat_MpuVector accel;
    bool has_gyro;
    CoprocStat_MpuVector gyro;
} CoprocStat_MpuStat;

typedef PB_BYTES_ARRAY_T(24) CoprocStat_SmartServoStat_data_t;
typedef struct _CoprocStat_SmartServoStat {
    CoprocStat_SmartServoStat_data_t data;
} CoprocStat_SmartServoStat;

typedef struct _CoprocStat {
    pb_size_t which_payload;
    union {
        None ledsStat;
        CoprocStat_ButtonsStat buttonsStat;
        None stupidServoStat;
        CoprocStat_UltrasoundStat ultrasoundStat;
        CoprocStat_PowerAdcStat powerAdcStat;
        CoprocStat_VersionStat versionStat;
        CoprocStat_MotorStat motorStat;
        CoprocStat_RtcStat rtcStat;
        CoprocStat_FaultStat faultStat;
        CoprocStat_MpuStat mpuStat;
        CoprocStat_SmartServoStat smartServoStat;
    } payload;
} CoprocStat;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _MotorMode_MIN MotorMode_POWER
#define _MotorMode_MAX MotorMode_COUPLE_POWER
#define _MotorMode_ARRAYSIZE ((MotorMode)(MotorMode_COUPLE_POWER+1))

#define _CoprocReq_LedsEnum_MIN CoprocReq_LedsEnum_NONE
#define _CoprocReq_LedsEnum_MAX CoprocReq_LedsEnum_L4
#define _CoprocReq_LedsEnum_ARRAYSIZE ((CoprocReq_LedsEnum)(CoprocReq_LedsEnum_L4+1))

#define _CoprocReq_OledColor_MIN CoprocReq_OledColor_OLED_BLACK
#define _CoprocReq_OledColor_MAX CoprocReq_OledColor_OLED_WHITE
#define _CoprocReq_OledColor_ARRAYSIZE ((CoprocReq_OledColor)(CoprocReq_OledColor_OLED_WHITE+1))

#define _CoprocReq_OledFont_MIN CoprocReq_OledFont_OLED_FONT_6X8
#define _CoprocReq_OledFont_MAX CoprocReq_OledFont_OLED_FONT_16X26
#define _CoprocReq_OledFont_ARRAYSIZE ((CoprocReq_OledFont)(CoprocReq_OledFont_OLED_FONT_16X26+1))

#define _CoprocStat_ButtonsEnum_MIN CoprocStat_ButtonsEnum_BNONE
#define _CoprocStat_ButtonsEnum_MAX CoprocStat_ButtonsEnum_BON
#define _CoprocStat_ButtonsEnum_ARRAYSIZE ((CoprocStat_ButtonsEnum)(CoprocStat_ButtonsEnum_BON+1))

#define _CoprocStat_RtcFlags_MIN CoprocStat_RtcFlags_RTC_NONE
#define _CoprocStat_RtcFlags_MAX CoprocStat_RtcFlags_RTC_ALARM
#define _CoprocStat_RtcFlags_ARRAYSIZE ((CoprocStat_RtcFlags)(CoprocStat_RtcFlags_RTC_ALARM+1))





#define CoprocReq_SetLeds_ledsOn_ENUMTYPE CoprocReq_LedsEnum











#define CoprocReq_OledReq_oledCmd_fill_ENUMTYPE CoprocReq_OledColor


#define CoprocReq_OledDrawPixel_color_ENUMTYPE CoprocReq_OledColor

#define CoprocReq_OledWriteString_font_ENUMTYPE CoprocReq_OledFont
#define CoprocReq_OledWriteString_color_ENUMTYPE CoprocReq_OledColor


#define CoprocReq_OledDrawLine_color_ENUMTYPE CoprocReq_OledColor

#define CoprocReq_OledDrawArc_color_ENUMTYPE CoprocReq_OledColor

#define CoprocReq_OledDrawCircle_color_ENUMTYPE CoprocReq_OledColor

#define CoprocReq_OledDrawRectangle_color_ENUMTYPE CoprocReq_OledColor






#define CoprocStat_ButtonsStat_buttonsPressed_ENUMTYPE CoprocStat_ButtonsEnum


#define CoprocStat_MotorStat_mode_ENUMTYPE MotorMode



#define CoprocStat_RtcStat_flags_ENUMTYPE CoprocStat_RtcFlags






/* Initializer values for message structs */
#define None_init_default                        {0}
#define RegCoefs_init_default                    {0, 0, 0}
#define MotorConfig_init_default                 {0, 0, 0}
#define CoprocReq_init_default                   {0, {None_init_default}}
#define CoprocReq_SetLeds_init_default           {_CoprocReq_LedsEnum_MIN}
#define CoprocReq_GetButtons_init_default        {0}
#define CoprocReq_SetStupidServo_init_default    {0, 0, {None_init_default}}
#define CoprocReq_UltrasoundReq_init_default     {0, 0, {None_init_default}}
#define CoprocReq_SetMotorCoupling_init_default  {0}
#define CoprocReq_MotorReq_init_default          {0, 0, {None_init_default}}
#define CoprocReq_MotorReq_SetPosition_init_default {0, 0}
#define CoprocReq_BuzzerReq_init_default         {0}
#define CoprocReq_CalibratePower_init_default    {0, 0, 0, 0}
#define CoprocReq_RtcReq_init_default            {0, {None_init_default}}
#define CoprocReq_I2cReq_init_default            {0, {CoprocReq_OledReq_init_default}}
#define CoprocReq_OledReq_init_default           {0, {CoprocReq_OledInit_init_default}}
#define CoprocReq_OledInit_init_default          {0, 0, 0, 0}
#define CoprocReq_OledDrawPixel_init_default     {0, 0, _CoprocReq_OledColor_MIN}
#define CoprocReq_OledWriteString_init_default   {"", _CoprocReq_OledFont_MIN, _CoprocReq_OledColor_MIN}
#define CoprocReq_OledSetCursor_init_default     {0, 0}
#define CoprocReq_OledDrawLine_init_default      {0, 0, 0, 0, _CoprocReq_OledColor_MIN}
#define CoprocReq_OledDrawArc_init_default       {0, 0, 0, 0, 0, _CoprocReq_OledColor_MIN}
#define CoprocReq_OledDrawCircle_init_default    {0, 0, 0, _CoprocReq_OledColor_MIN}
#define CoprocReq_OledDrawRectangle_init_default {0, 0, 0, 0, _CoprocReq_OledColor_MIN}
#define CoprocReq_MpuReq_init_default            {0, {None_init_default}}
#define CoprocReq_EspWatchdogSettings_init_default {0}
#define CoprocReq_CoprocStartupMessage_init_default {0, 0, 0, false, CoprocReq_EspWatchdogSettings_init_default}
#define CoprocReq_SmartServoReq_init_default     {0, {0, {0}}}
#define CoprocStat_init_default                  {0, {None_init_default}}
#define CoprocStat_ButtonsStat_init_default      {_CoprocStat_ButtonsEnum_MIN}
#define CoprocStat_UltrasoundStat_init_default   {0, 0}
#define CoprocStat_MotorStat_init_default        {0, _MotorMode_MIN, 0, 0, 0}
#define CoprocStat_PowerAdcStat_init_default     {0, 0, 0}
#define CoprocStat_VersionStat_init_default      {{0}, 0, 0}
#define CoprocStat_RtcStat_init_default          {0, 0, _CoprocStat_RtcFlags_MIN}
#define CoprocStat_FaultStat_init_default        {0, {None_init_default}}
#define CoprocStat_MpuStat_init_default          {0, false, CoprocStat_MpuVector_init_default, false, CoprocStat_MpuVector_init_default}
#define CoprocStat_MpuVector_init_default        {0, 0, 0}
#define CoprocStat_SmartServoStat_init_default   {{0, {0}}}
#define None_init_zero                           {0}
#define RegCoefs_init_zero                       {0, 0, 0}
#define MotorConfig_init_zero                    {0, 0, 0}
#define CoprocReq_init_zero                      {0, {None_init_zero}}
#define CoprocReq_SetLeds_init_zero              {_CoprocReq_LedsEnum_MIN}
#define CoprocReq_GetButtons_init_zero           {0}
#define CoprocReq_SetStupidServo_init_zero       {0, 0, {None_init_zero}}
#define CoprocReq_UltrasoundReq_init_zero        {0, 0, {None_init_zero}}
#define CoprocReq_SetMotorCoupling_init_zero     {0}
#define CoprocReq_MotorReq_init_zero             {0, 0, {None_init_zero}}
#define CoprocReq_MotorReq_SetPosition_init_zero {0, 0}
#define CoprocReq_BuzzerReq_init_zero            {0}
#define CoprocReq_CalibratePower_init_zero       {0, 0, 0, 0}
#define CoprocReq_RtcReq_init_zero               {0, {None_init_zero}}
#define CoprocReq_I2cReq_init_zero               {0, {CoprocReq_OledReq_init_zero}}
#define CoprocReq_OledReq_init_zero              {0, {CoprocReq_OledInit_init_zero}}
#define CoprocReq_OledInit_init_zero             {0, 0, 0, 0}
#define CoprocReq_OledDrawPixel_init_zero        {0, 0, _CoprocReq_OledColor_MIN}
#define CoprocReq_OledWriteString_init_zero      {"", _CoprocReq_OledFont_MIN, _CoprocReq_OledColor_MIN}
#define CoprocReq_OledSetCursor_init_zero        {0, 0}
#define CoprocReq_OledDrawLine_init_zero         {0, 0, 0, 0, _CoprocReq_OledColor_MIN}
#define CoprocReq_OledDrawArc_init_zero          {0, 0, 0, 0, 0, _CoprocReq_OledColor_MIN}
#define CoprocReq_OledDrawCircle_init_zero       {0, 0, 0, _CoprocReq_OledColor_MIN}
#define CoprocReq_OledDrawRectangle_init_zero    {0, 0, 0, 0, _CoprocReq_OledColor_MIN}
#define CoprocReq_MpuReq_init_zero               {0, {None_init_zero}}
#define CoprocReq_EspWatchdogSettings_init_zero  {0}
#define CoprocReq_CoprocStartupMessage_init_zero {0, 0, 0, false, CoprocReq_EspWatchdogSettings_init_zero}
#define CoprocReq_SmartServoReq_init_zero        {0, {0, {0}}}
#define CoprocStat_init_zero                     {0, {None_init_zero}}
#define CoprocStat_ButtonsStat_init_zero         {_CoprocStat_ButtonsEnum_MIN}
#define CoprocStat_UltrasoundStat_init_zero      {0, 0}
#define CoprocStat_MotorStat_init_zero           {0, _MotorMode_MIN, 0, 0, 0}
#define CoprocStat_PowerAdcStat_init_zero        {0, 0, 0}
#define CoprocStat_VersionStat_init_zero         {{0}, 0, 0}
#define CoprocStat_RtcStat_init_zero             {0, 0, _CoprocStat_RtcFlags_MIN}
#define CoprocStat_FaultStat_init_zero           {0, {None_init_zero}}
#define CoprocStat_MpuStat_init_zero             {0, false, CoprocStat_MpuVector_init_zero, false, CoprocStat_MpuVector_init_zero}
#define CoprocStat_MpuVector_init_zero           {0, 0, 0}
#define CoprocStat_SmartServoStat_init_zero      {{0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define RegCoefs_p_tag                           1
#define RegCoefs_i_tag                           2
#define RegCoefs_d_tag                           3
#define MotorConfig_velEpsilon_tag               1
#define MotorConfig_posEpsilon_tag               2
#define MotorConfig_maxAccel_tag                 3
#define CoprocReq_SetLeds_ledsOn_tag             1
#define CoprocReq_SetStupidServo_servoIndex_tag  1
#define CoprocReq_SetStupidServo_disable_tag     4
#define CoprocReq_SetStupidServo_setPosition_tag 5
#define CoprocReq_UltrasoundReq_utsIndex_tag     1
#define CoprocReq_UltrasoundReq_singlePing_tag   4
#define CoprocReq_SetMotorCoupling_coupleAxis_tag 1
#define CoprocReq_MotorReq_SetPosition_targetPosition_tag 1
#define CoprocReq_MotorReq_SetPosition_runningVelocity_tag 2
#define CoprocReq_MotorReq_motorIndex_tag        1
#define CoprocReq_MotorReq_getState_tag          4
#define CoprocReq_MotorReq_setPower_tag          5
#define CoprocReq_MotorReq_setBrake_tag          6
#define CoprocReq_MotorReq_setVelocity_tag       7
#define CoprocReq_MotorReq_homePosition_tag      8
#define CoprocReq_MotorReq_setPosition_tag       10
#define CoprocReq_MotorReq_addPosition_tag       11
#define CoprocReq_MotorReq_setVelocityRegCoefs_tag 16
#define CoprocReq_MotorReq_setPositionRegCoefs_tag 17
#define CoprocReq_MotorReq_setConfig_tag         18
#define CoprocReq_MotorReq_setCoupling_tag       19
#define CoprocReq_BuzzerReq_on_tag               1
#define CoprocReq_CalibratePower_vccMv_tag       1
#define CoprocReq_CalibratePower_battMidMv_tag   2
#define CoprocReq_CalibratePower_vRef33Mv_tag    3
#define CoprocReq_CalibratePower_temperatureC_tag 4
#define CoprocReq_RtcReq_get_tag                 1
#define CoprocReq_RtcReq_setTime_tag             2
#define CoprocReq_RtcReq_setAlarm_tag            3
#define CoprocReq_OledInit_height_tag            1
#define CoprocReq_OledInit_width_tag             2
#define CoprocReq_OledInit_rotate_tag            3
#define CoprocReq_OledInit_inverseColor_tag      4
#define CoprocReq_OledDrawPixel_x_tag            1
#define CoprocReq_OledDrawPixel_y_tag            2
#define CoprocReq_OledDrawPixel_color_tag        3
#define CoprocReq_OledWriteString_text_tag       1
#define CoprocReq_OledWriteString_font_tag       2
#define CoprocReq_OledWriteString_color_tag      3
#define CoprocReq_OledSetCursor_x_tag            1
#define CoprocReq_OledSetCursor_y_tag            2
#define CoprocReq_OledDrawLine_x1_tag            1
#define CoprocReq_OledDrawLine_y1_tag            2
#define CoprocReq_OledDrawLine_x2_tag            3
#define CoprocReq_OledDrawLine_y2_tag            4
#define CoprocReq_OledDrawLine_color_tag         5
#define CoprocReq_OledDrawArc_x_tag              1
#define CoprocReq_OledDrawArc_y_tag              2
#define CoprocReq_OledDrawArc_radius_tag         3
#define CoprocReq_OledDrawArc_start_angle_tag    4
#define CoprocReq_OledDrawArc_sweep_tag          5
#define CoprocReq_OledDrawArc_color_tag          6
#define CoprocReq_OledDrawCircle_x_tag           1
#define CoprocReq_OledDrawCircle_y_tag           2
#define CoprocReq_OledDrawCircle_radius_tag      3
#define CoprocReq_OledDrawCircle_color_tag       4
#define CoprocReq_OledDrawRectangle_x1_tag       1
#define CoprocReq_OledDrawRectangle_y1_tag       2
#define CoprocReq_OledDrawRectangle_x2_tag       3
#define CoprocReq_OledDrawRectangle_y2_tag       4
#define CoprocReq_OledDrawRectangle_color_tag    5
#define CoprocReq_OledReq_init_tag               1
#define CoprocReq_OledReq_fill_tag               2
#define CoprocReq_OledReq_update_tag             3
#define CoprocReq_OledReq_drawPixel_tag          4
#define CoprocReq_OledReq_writeString_tag        5
#define CoprocReq_OledReq_setCursor_tag          6
#define CoprocReq_OledReq_drawLine_tag           7
#define CoprocReq_OledReq_drawArc_tag            8
#define CoprocReq_OledReq_drawCircle_tag         9
#define CoprocReq_OledReq_drawRectangle_tag      10
#define CoprocReq_MpuReq_init_tag                1
#define CoprocReq_MpuReq_oneSend_tag             2
#define CoprocReq_MpuReq_startSend_tag           3
#define CoprocReq_MpuReq_stopSend_tag            4
#define CoprocReq_MpuReq_setCompressCoef_tag     5
#define CoprocReq_MpuReq_getCompressCoef_tag     6
#define CoprocReq_I2cReq_oledReq_tag             1
#define CoprocReq_I2cReq_mpuReq_tag              2
#define CoprocReq_EspWatchdogSettings_disable_tag 1
#define CoprocReq_CoprocStartupMessage_getButtons_tag 1
#define CoprocReq_CoprocStartupMessage_getVersion_tag 2
#define CoprocReq_CoprocStartupMessage_getRtc_tag 3
#define CoprocReq_CoprocStartupMessage_espWatchdogSettings_tag 4
#define CoprocReq_SmartServoReq_expect_response_tag 1
#define CoprocReq_SmartServoReq_data_tag         2
#define CoprocReq_keepalive_tag                  1
#define CoprocReq_setLeds_tag                    4
#define CoprocReq_getButtons_tag                 5
#define CoprocReq_setStupidServo_tag             6
#define CoprocReq_ultrasoundReq_tag              7
#define CoprocReq_motorReq_tag                   8
#define CoprocReq_buzzerReq_tag                  9
#define CoprocReq_calibratePower_tag             10
#define CoprocReq_shutdownPower_tag              11
#define CoprocReq_versionReq_tag                 12
#define CoprocReq_rtcReq_tag                     13
#define CoprocReq_i2cReq_tag                     14
#define CoprocReq_espWatchdogSettings_tag        15
#define CoprocReq_coprocStartupMessage_tag       16
#define CoprocReq_smartServoReq_tag              17
#define CoprocStat_ButtonsStat_buttonsPressed_tag 1
#define CoprocStat_UltrasoundStat_utsIndex_tag   1
#define CoprocStat_UltrasoundStat_roundtripMicrosecs_tag 2
#define CoprocStat_MotorStat_motorIndex_tag      1
#define CoprocStat_MotorStat_mode_tag            2
#define CoprocStat_MotorStat_power_tag           3
#define CoprocStat_MotorStat_velocity_tag        4
#define CoprocStat_MotorStat_position_tag        5
#define CoprocStat_PowerAdcStat_vccMv_tag        1
#define CoprocStat_PowerAdcStat_battMidMv_tag    2
#define CoprocStat_PowerAdcStat_temperatureC_tag 3
#define CoprocStat_VersionStat_revision_tag      1
#define CoprocStat_VersionStat_number_tag        2
#define CoprocStat_VersionStat_dirty_tag         3
#define CoprocStat_RtcStat_time_tag              1
#define CoprocStat_RtcStat_alarm_tag             2
#define CoprocStat_RtcStat_flags_tag             3
#define CoprocStat_FaultStat_oledFault_tag       1
#define CoprocStat_FaultStat_mpuFault_tag        2
#define CoprocStat_MpuVector_x_tag               1
#define CoprocStat_MpuVector_y_tag               2
#define CoprocStat_MpuVector_z_tag               3
#define CoprocStat_MpuStat_compressCoef_tag      1
#define CoprocStat_MpuStat_accel_tag             2
#define CoprocStat_MpuStat_gyro_tag              3
#define CoprocStat_SmartServoStat_data_tag       1
#define CoprocStat_ledsStat_tag                  4
#define CoprocStat_buttonsStat_tag               5
#define CoprocStat_stupidServoStat_tag           6
#define CoprocStat_ultrasoundStat_tag            7
#define CoprocStat_powerAdcStat_tag              8
#define CoprocStat_versionStat_tag               9
#define CoprocStat_motorStat_tag                 10
#define CoprocStat_rtcStat_tag                   11
#define CoprocStat_faultStat_tag                 12
#define CoprocStat_mpuStat_tag                   13
#define CoprocStat_smartServoStat_tag            14

/* Struct field encoding specification for nanopb */
#define None_FIELDLIST(X, a) \

#define None_CALLBACK NULL
#define None_DEFAULT NULL

#define RegCoefs_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   p,                 1) \
X(a, STATIC,   SINGULAR, UINT32,   i,                 2) \
X(a, STATIC,   SINGULAR, UINT32,   d,                 3)
#define RegCoefs_CALLBACK NULL
#define RegCoefs_DEFAULT NULL

#define MotorConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   velEpsilon,        1) \
X(a, STATIC,   SINGULAR, UINT32,   posEpsilon,        2) \
X(a, STATIC,   SINGULAR, UINT32,   maxAccel,          3)
#define MotorConfig_CALLBACK NULL
#define MotorConfig_DEFAULT NULL

#define CoprocReq_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,keepalive,payload.keepalive),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,setLeds,payload.setLeds),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,getButtons,payload.getButtons),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,setStupidServo,payload.setStupidServo),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ultrasoundReq,payload.ultrasoundReq),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,motorReq,payload.motorReq),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,buzzerReq,payload.buzzerReq),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,calibratePower,payload.calibratePower),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,shutdownPower,payload.shutdownPower),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,versionReq,payload.versionReq),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,rtcReq,payload.rtcReq),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,i2cReq,payload.i2cReq),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,espWatchdogSettings,payload.espWatchdogSettings),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,coprocStartupMessage,payload.coprocStartupMessage),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,smartServoReq,payload.smartServoReq),  17)
#define CoprocReq_CALLBACK NULL
#define CoprocReq_DEFAULT NULL
#define CoprocReq_payload_keepalive_MSGTYPE None
#define CoprocReq_payload_setLeds_MSGTYPE CoprocReq_SetLeds
#define CoprocReq_payload_getButtons_MSGTYPE CoprocReq_GetButtons
#define CoprocReq_payload_setStupidServo_MSGTYPE CoprocReq_SetStupidServo
#define CoprocReq_payload_ultrasoundReq_MSGTYPE CoprocReq_UltrasoundReq
#define CoprocReq_payload_motorReq_MSGTYPE CoprocReq_MotorReq
#define CoprocReq_payload_buzzerReq_MSGTYPE CoprocReq_BuzzerReq
#define CoprocReq_payload_calibratePower_MSGTYPE CoprocReq_CalibratePower
#define CoprocReq_payload_shutdownPower_MSGTYPE None
#define CoprocReq_payload_versionReq_MSGTYPE None
#define CoprocReq_payload_rtcReq_MSGTYPE CoprocReq_RtcReq
#define CoprocReq_payload_i2cReq_MSGTYPE CoprocReq_I2cReq
#define CoprocReq_payload_espWatchdogSettings_MSGTYPE CoprocReq_EspWatchdogSettings
#define CoprocReq_payload_coprocStartupMessage_MSGTYPE CoprocReq_CoprocStartupMessage
#define CoprocReq_payload_smartServoReq_MSGTYPE CoprocReq_SmartServoReq

#define CoprocReq_SetLeds_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    ledsOn,            1)
#define CoprocReq_SetLeds_CALLBACK NULL
#define CoprocReq_SetLeds_DEFAULT NULL

#define CoprocReq_GetButtons_FIELDLIST(X, a) \

#define CoprocReq_GetButtons_CALLBACK NULL
#define CoprocReq_GetButtons_DEFAULT NULL

#define CoprocReq_SetStupidServo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   servoIndex,        1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (servoCmd,disable,servoCmd.disable),   4) \
X(a, STATIC,   ONEOF,    FLOAT,    (servoCmd,setPosition,servoCmd.setPosition),   5)
#define CoprocReq_SetStupidServo_CALLBACK NULL
#define CoprocReq_SetStupidServo_DEFAULT NULL
#define CoprocReq_SetStupidServo_servoCmd_disable_MSGTYPE None

#define CoprocReq_UltrasoundReq_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   utsIndex,          1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (utsCmd,singlePing,utsCmd.singlePing),   4)
#define CoprocReq_UltrasoundReq_CALLBACK NULL
#define CoprocReq_UltrasoundReq_DEFAULT NULL
#define CoprocReq_UltrasoundReq_utsCmd_singlePing_MSGTYPE None

#define CoprocReq_SetMotorCoupling_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   coupleAxis,        1)
#define CoprocReq_SetMotorCoupling_CALLBACK NULL
#define CoprocReq_SetMotorCoupling_DEFAULT NULL

#define CoprocReq_MotorReq_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   motorIndex,        1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (motorCmd,getState,motorCmd.getState),   4) \
X(a, STATIC,   ONEOF,    SINT32,   (motorCmd,setPower,motorCmd.setPower),   5) \
X(a, STATIC,   ONEOF,    SINT32,   (motorCmd,setBrake,motorCmd.setBrake),   6) \
X(a, STATIC,   ONEOF,    SINT32,   (motorCmd,setVelocity,motorCmd.setVelocity),   7) \
X(a, STATIC,   ONEOF,    SINT32,   (motorCmd,homePosition,motorCmd.homePosition),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (motorCmd,setPosition,motorCmd.setPosition),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (motorCmd,addPosition,motorCmd.addPosition),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (motorCmd,setVelocityRegCoefs,motorCmd.setVelocityRegCoefs),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (motorCmd,setPositionRegCoefs,motorCmd.setPositionRegCoefs),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (motorCmd,setConfig,motorCmd.setConfig),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (motorCmd,setCoupling,motorCmd.setCoupling),  19)
#define CoprocReq_MotorReq_CALLBACK NULL
#define CoprocReq_MotorReq_DEFAULT NULL
#define CoprocReq_MotorReq_motorCmd_getState_MSGTYPE None
#define CoprocReq_MotorReq_motorCmd_setPosition_MSGTYPE CoprocReq_MotorReq_SetPosition
#define CoprocReq_MotorReq_motorCmd_addPosition_MSGTYPE CoprocReq_MotorReq_SetPosition
#define CoprocReq_MotorReq_motorCmd_setVelocityRegCoefs_MSGTYPE RegCoefs
#define CoprocReq_MotorReq_motorCmd_setPositionRegCoefs_MSGTYPE RegCoefs
#define CoprocReq_MotorReq_motorCmd_setConfig_MSGTYPE MotorConfig
#define CoprocReq_MotorReq_motorCmd_setCoupling_MSGTYPE CoprocReq_SetMotorCoupling

#define CoprocReq_MotorReq_SetPosition_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   targetPosition,    1) \
X(a, STATIC,   SINGULAR, SINT32,   runningVelocity,   2)
#define CoprocReq_MotorReq_SetPosition_CALLBACK NULL
#define CoprocReq_MotorReq_SetPosition_DEFAULT NULL

#define CoprocReq_BuzzerReq_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     on,                1)
#define CoprocReq_BuzzerReq_CALLBACK NULL
#define CoprocReq_BuzzerReq_DEFAULT NULL

#define CoprocReq_CalibratePower_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   vccMv,             1) \
X(a, STATIC,   SINGULAR, UINT32,   battMidMv,         2) \
X(a, STATIC,   SINGULAR, UINT32,   vRef33Mv,          3) \
X(a, STATIC,   SINGULAR, UINT32,   temperatureC,      4)
#define CoprocReq_CalibratePower_CALLBACK NULL
#define CoprocReq_CalibratePower_DEFAULT NULL

#define CoprocReq_RtcReq_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (rtcCmd,get,rtcCmd.get),   1) \
X(a, STATIC,   ONEOF,    UINT32,   (rtcCmd,setTime,rtcCmd.setTime),   2) \
X(a, STATIC,   ONEOF,    UINT32,   (rtcCmd,setAlarm,rtcCmd.setAlarm),   3)
#define CoprocReq_RtcReq_CALLBACK NULL
#define CoprocReq_RtcReq_DEFAULT NULL
#define CoprocReq_RtcReq_rtcCmd_get_MSGTYPE None

#define CoprocReq_I2cReq_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,oledReq,payload.oledReq),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,mpuReq,payload.mpuReq),   2)
#define CoprocReq_I2cReq_CALLBACK NULL
#define CoprocReq_I2cReq_DEFAULT NULL
#define CoprocReq_I2cReq_payload_oledReq_MSGTYPE CoprocReq_OledReq
#define CoprocReq_I2cReq_payload_mpuReq_MSGTYPE CoprocReq_MpuReq

#define CoprocReq_OledReq_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (oledCmd,init,oledCmd.init),   1) \
X(a, STATIC,   ONEOF,    UENUM,    (oledCmd,fill,oledCmd.fill),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (oledCmd,update,oledCmd.update),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (oledCmd,drawPixel,oledCmd.drawPixel),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (oledCmd,writeString,oledCmd.writeString),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (oledCmd,setCursor,oledCmd.setCursor),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (oledCmd,drawLine,oledCmd.drawLine),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (oledCmd,drawArc,oledCmd.drawArc),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (oledCmd,drawCircle,oledCmd.drawCircle),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (oledCmd,drawRectangle,oledCmd.drawRectangle),  10)
#define CoprocReq_OledReq_CALLBACK NULL
#define CoprocReq_OledReq_DEFAULT NULL
#define CoprocReq_OledReq_oledCmd_init_MSGTYPE CoprocReq_OledInit
#define CoprocReq_OledReq_oledCmd_update_MSGTYPE None
#define CoprocReq_OledReq_oledCmd_drawPixel_MSGTYPE CoprocReq_OledDrawPixel
#define CoprocReq_OledReq_oledCmd_writeString_MSGTYPE CoprocReq_OledWriteString
#define CoprocReq_OledReq_oledCmd_setCursor_MSGTYPE CoprocReq_OledSetCursor
#define CoprocReq_OledReq_oledCmd_drawLine_MSGTYPE CoprocReq_OledDrawLine
#define CoprocReq_OledReq_oledCmd_drawArc_MSGTYPE CoprocReq_OledDrawArc
#define CoprocReq_OledReq_oledCmd_drawCircle_MSGTYPE CoprocReq_OledDrawCircle
#define CoprocReq_OledReq_oledCmd_drawRectangle_MSGTYPE CoprocReq_OledDrawRectangle

#define CoprocReq_OledInit_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   height,            1) \
X(a, STATIC,   SINGULAR, UINT32,   width,             2) \
X(a, STATIC,   SINGULAR, BOOL,     rotate,            3) \
X(a, STATIC,   SINGULAR, BOOL,     inverseColor,      4)
#define CoprocReq_OledInit_CALLBACK NULL
#define CoprocReq_OledInit_DEFAULT NULL

#define CoprocReq_OledDrawPixel_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   x,                 1) \
X(a, STATIC,   SINGULAR, UINT32,   y,                 2) \
X(a, STATIC,   SINGULAR, UENUM,    color,             3)
#define CoprocReq_OledDrawPixel_CALLBACK NULL
#define CoprocReq_OledDrawPixel_DEFAULT NULL

#define CoprocReq_OledWriteString_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   text,              1) \
X(a, STATIC,   SINGULAR, UENUM,    font,              2) \
X(a, STATIC,   SINGULAR, UENUM,    color,             3)
#define CoprocReq_OledWriteString_CALLBACK NULL
#define CoprocReq_OledWriteString_DEFAULT NULL

#define CoprocReq_OledSetCursor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   x,                 1) \
X(a, STATIC,   SINGULAR, UINT32,   y,                 2)
#define CoprocReq_OledSetCursor_CALLBACK NULL
#define CoprocReq_OledSetCursor_DEFAULT NULL

#define CoprocReq_OledDrawLine_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   x1,                1) \
X(a, STATIC,   SINGULAR, UINT32,   y1,                2) \
X(a, STATIC,   SINGULAR, UINT32,   x2,                3) \
X(a, STATIC,   SINGULAR, UINT32,   y2,                4) \
X(a, STATIC,   SINGULAR, UENUM,    color,             5)
#define CoprocReq_OledDrawLine_CALLBACK NULL
#define CoprocReq_OledDrawLine_DEFAULT NULL

#define CoprocReq_OledDrawArc_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   x,                 1) \
X(a, STATIC,   SINGULAR, UINT32,   y,                 2) \
X(a, STATIC,   SINGULAR, UINT32,   radius,            3) \
X(a, STATIC,   SINGULAR, UINT32,   start_angle,       4) \
X(a, STATIC,   SINGULAR, UINT32,   sweep,             5) \
X(a, STATIC,   SINGULAR, UENUM,    color,             6)
#define CoprocReq_OledDrawArc_CALLBACK NULL
#define CoprocReq_OledDrawArc_DEFAULT NULL

#define CoprocReq_OledDrawCircle_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   x,                 1) \
X(a, STATIC,   SINGULAR, UINT32,   y,                 2) \
X(a, STATIC,   SINGULAR, UINT32,   radius,            3) \
X(a, STATIC,   SINGULAR, UENUM,    color,             4)
#define CoprocReq_OledDrawCircle_CALLBACK NULL
#define CoprocReq_OledDrawCircle_DEFAULT NULL

#define CoprocReq_OledDrawRectangle_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   x1,                1) \
X(a, STATIC,   SINGULAR, UINT32,   y1,                2) \
X(a, STATIC,   SINGULAR, UINT32,   x2,                3) \
X(a, STATIC,   SINGULAR, UINT32,   y2,                4) \
X(a, STATIC,   SINGULAR, UENUM,    color,             5)
#define CoprocReq_OledDrawRectangle_CALLBACK NULL
#define CoprocReq_OledDrawRectangle_DEFAULT NULL

#define CoprocReq_MpuReq_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (mpuCmd,init,mpuCmd.init),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (mpuCmd,oneSend,mpuCmd.oneSend),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (mpuCmd,startSend,mpuCmd.startSend),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (mpuCmd,stopSend,mpuCmd.stopSend),   4) \
X(a, STATIC,   ONEOF,    UINT32,   (mpuCmd,setCompressCoef,mpuCmd.setCompressCoef),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (mpuCmd,getCompressCoef,mpuCmd.getCompressCoef),   6)
#define CoprocReq_MpuReq_CALLBACK NULL
#define CoprocReq_MpuReq_DEFAULT NULL
#define CoprocReq_MpuReq_mpuCmd_init_MSGTYPE None
#define CoprocReq_MpuReq_mpuCmd_oneSend_MSGTYPE None
#define CoprocReq_MpuReq_mpuCmd_startSend_MSGTYPE None
#define CoprocReq_MpuReq_mpuCmd_stopSend_MSGTYPE None
#define CoprocReq_MpuReq_mpuCmd_getCompressCoef_MSGTYPE None

#define CoprocReq_EspWatchdogSettings_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     disable,           1)
#define CoprocReq_EspWatchdogSettings_CALLBACK NULL
#define CoprocReq_EspWatchdogSettings_DEFAULT NULL

#define CoprocReq_CoprocStartupMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     getButtons,        1) \
X(a, STATIC,   SINGULAR, BOOL,     getVersion,        2) \
X(a, STATIC,   SINGULAR, BOOL,     getRtc,            3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  espWatchdogSettings,   4)
#define CoprocReq_CoprocStartupMessage_CALLBACK NULL
#define CoprocReq_CoprocStartupMessage_DEFAULT NULL
#define CoprocReq_CoprocStartupMessage_espWatchdogSettings_MSGTYPE CoprocReq_EspWatchdogSettings

#define CoprocReq_SmartServoReq_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     expect_response,   1) \
X(a, STATIC,   SINGULAR, BYTES,    data,              2)
#define CoprocReq_SmartServoReq_CALLBACK NULL
#define CoprocReq_SmartServoReq_DEFAULT NULL

#define CoprocStat_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ledsStat,payload.ledsStat),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,buttonsStat,payload.buttonsStat),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,stupidServoStat,payload.stupidServoStat),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ultrasoundStat,payload.ultrasoundStat),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,powerAdcStat,payload.powerAdcStat),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,versionStat,payload.versionStat),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,motorStat,payload.motorStat),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,rtcStat,payload.rtcStat),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,faultStat,payload.faultStat),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,mpuStat,payload.mpuStat),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,smartServoStat,payload.smartServoStat),  14)
#define CoprocStat_CALLBACK NULL
#define CoprocStat_DEFAULT NULL
#define CoprocStat_payload_ledsStat_MSGTYPE None
#define CoprocStat_payload_buttonsStat_MSGTYPE CoprocStat_ButtonsStat
#define CoprocStat_payload_stupidServoStat_MSGTYPE None
#define CoprocStat_payload_ultrasoundStat_MSGTYPE CoprocStat_UltrasoundStat
#define CoprocStat_payload_powerAdcStat_MSGTYPE CoprocStat_PowerAdcStat
#define CoprocStat_payload_versionStat_MSGTYPE CoprocStat_VersionStat
#define CoprocStat_payload_motorStat_MSGTYPE CoprocStat_MotorStat
#define CoprocStat_payload_rtcStat_MSGTYPE CoprocStat_RtcStat
#define CoprocStat_payload_faultStat_MSGTYPE CoprocStat_FaultStat
#define CoprocStat_payload_mpuStat_MSGTYPE CoprocStat_MpuStat
#define CoprocStat_payload_smartServoStat_MSGTYPE CoprocStat_SmartServoStat

#define CoprocStat_ButtonsStat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    buttonsPressed,    1)
#define CoprocStat_ButtonsStat_CALLBACK NULL
#define CoprocStat_ButtonsStat_DEFAULT NULL

#define CoprocStat_UltrasoundStat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   utsIndex,          1) \
X(a, STATIC,   SINGULAR, UINT32,   roundtripMicrosecs,   2)
#define CoprocStat_UltrasoundStat_CALLBACK NULL
#define CoprocStat_UltrasoundStat_DEFAULT NULL

#define CoprocStat_MotorStat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   motorIndex,        1) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              2) \
X(a, STATIC,   SINGULAR, SINT32,   power,             3) \
X(a, STATIC,   SINGULAR, SINT32,   velocity,          4) \
X(a, STATIC,   SINGULAR, SINT32,   position,          5)
#define CoprocStat_MotorStat_CALLBACK NULL
#define CoprocStat_MotorStat_DEFAULT NULL

#define CoprocStat_PowerAdcStat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   vccMv,             1) \
X(a, STATIC,   SINGULAR, UINT32,   battMidMv,         2) \
X(a, STATIC,   SINGULAR, INT32,    temperatureC,      3)
#define CoprocStat_PowerAdcStat_CALLBACK NULL
#define CoprocStat_PowerAdcStat_DEFAULT NULL

#define CoprocStat_VersionStat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, revision,          1) \
X(a, STATIC,   SINGULAR, UINT32,   number,            2) \
X(a, STATIC,   SINGULAR, BOOL,     dirty,             3)
#define CoprocStat_VersionStat_CALLBACK NULL
#define CoprocStat_VersionStat_DEFAULT NULL

#define CoprocStat_RtcStat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   time,              1) \
X(a, STATIC,   SINGULAR, UINT32,   alarm,             2) \
X(a, STATIC,   SINGULAR, UENUM,    flags,             3)
#define CoprocStat_RtcStat_CALLBACK NULL
#define CoprocStat_RtcStat_DEFAULT NULL

#define CoprocStat_FaultStat_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (fault,oledFault,fault.oledFault),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (fault,mpuFault,fault.mpuFault),   2)
#define CoprocStat_FaultStat_CALLBACK NULL
#define CoprocStat_FaultStat_DEFAULT NULL
#define CoprocStat_FaultStat_fault_oledFault_MSGTYPE None
#define CoprocStat_FaultStat_fault_mpuFault_MSGTYPE None

#define CoprocStat_MpuStat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   compressCoef,      1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  accel,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gyro,              3)
#define CoprocStat_MpuStat_CALLBACK NULL
#define CoprocStat_MpuStat_DEFAULT NULL
#define CoprocStat_MpuStat_accel_MSGTYPE CoprocStat_MpuVector
#define CoprocStat_MpuStat_gyro_MSGTYPE CoprocStat_MpuVector

#define CoprocStat_MpuVector_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    x,                 1) \
X(a, STATIC,   SINGULAR, INT32,    y,                 2) \
X(a, STATIC,   SINGULAR, INT32,    z,                 3)
#define CoprocStat_MpuVector_CALLBACK NULL
#define CoprocStat_MpuVector_DEFAULT NULL

#define CoprocStat_SmartServoStat_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    data,              1)
#define CoprocStat_SmartServoStat_CALLBACK NULL
#define CoprocStat_SmartServoStat_DEFAULT NULL

extern const pb_msgdesc_t None_msg;
extern const pb_msgdesc_t RegCoefs_msg;
extern const pb_msgdesc_t MotorConfig_msg;
extern const pb_msgdesc_t CoprocReq_msg;
extern const pb_msgdesc_t CoprocReq_SetLeds_msg;
extern const pb_msgdesc_t CoprocReq_GetButtons_msg;
extern const pb_msgdesc_t CoprocReq_SetStupidServo_msg;
extern const pb_msgdesc_t CoprocReq_UltrasoundReq_msg;
extern const pb_msgdesc_t CoprocReq_SetMotorCoupling_msg;
extern const pb_msgdesc_t CoprocReq_MotorReq_msg;
extern const pb_msgdesc_t CoprocReq_MotorReq_SetPosition_msg;
extern const pb_msgdesc_t CoprocReq_BuzzerReq_msg;
extern const pb_msgdesc_t CoprocReq_CalibratePower_msg;
extern const pb_msgdesc_t CoprocReq_RtcReq_msg;
extern const pb_msgdesc_t CoprocReq_I2cReq_msg;
extern const pb_msgdesc_t CoprocReq_OledReq_msg;
extern const pb_msgdesc_t CoprocReq_OledInit_msg;
extern const pb_msgdesc_t CoprocReq_OledDrawPixel_msg;
extern const pb_msgdesc_t CoprocReq_OledWriteString_msg;
extern const pb_msgdesc_t CoprocReq_OledSetCursor_msg;
extern const pb_msgdesc_t CoprocReq_OledDrawLine_msg;
extern const pb_msgdesc_t CoprocReq_OledDrawArc_msg;
extern const pb_msgdesc_t CoprocReq_OledDrawCircle_msg;
extern const pb_msgdesc_t CoprocReq_OledDrawRectangle_msg;
extern const pb_msgdesc_t CoprocReq_MpuReq_msg;
extern const pb_msgdesc_t CoprocReq_EspWatchdogSettings_msg;
extern const pb_msgdesc_t CoprocReq_CoprocStartupMessage_msg;
extern const pb_msgdesc_t CoprocReq_SmartServoReq_msg;
extern const pb_msgdesc_t CoprocStat_msg;
extern const pb_msgdesc_t CoprocStat_ButtonsStat_msg;
extern const pb_msgdesc_t CoprocStat_UltrasoundStat_msg;
extern const pb_msgdesc_t CoprocStat_MotorStat_msg;
extern const pb_msgdesc_t CoprocStat_PowerAdcStat_msg;
extern const pb_msgdesc_t CoprocStat_VersionStat_msg;
extern const pb_msgdesc_t CoprocStat_RtcStat_msg;
extern const pb_msgdesc_t CoprocStat_FaultStat_msg;
extern const pb_msgdesc_t CoprocStat_MpuStat_msg;
extern const pb_msgdesc_t CoprocStat_MpuVector_msg;
extern const pb_msgdesc_t CoprocStat_SmartServoStat_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define None_fields &None_msg
#define RegCoefs_fields &RegCoefs_msg
#define MotorConfig_fields &MotorConfig_msg
#define CoprocReq_fields &CoprocReq_msg
#define CoprocReq_SetLeds_fields &CoprocReq_SetLeds_msg
#define CoprocReq_GetButtons_fields &CoprocReq_GetButtons_msg
#define CoprocReq_SetStupidServo_fields &CoprocReq_SetStupidServo_msg
#define CoprocReq_UltrasoundReq_fields &CoprocReq_UltrasoundReq_msg
#define CoprocReq_SetMotorCoupling_fields &CoprocReq_SetMotorCoupling_msg
#define CoprocReq_MotorReq_fields &CoprocReq_MotorReq_msg
#define CoprocReq_MotorReq_SetPosition_fields &CoprocReq_MotorReq_SetPosition_msg
#define CoprocReq_BuzzerReq_fields &CoprocReq_BuzzerReq_msg
#define CoprocReq_CalibratePower_fields &CoprocReq_CalibratePower_msg
#define CoprocReq_RtcReq_fields &CoprocReq_RtcReq_msg
#define CoprocReq_I2cReq_fields &CoprocReq_I2cReq_msg
#define CoprocReq_OledReq_fields &CoprocReq_OledReq_msg
#define CoprocReq_OledInit_fields &CoprocReq_OledInit_msg
#define CoprocReq_OledDrawPixel_fields &CoprocReq_OledDrawPixel_msg
#define CoprocReq_OledWriteString_fields &CoprocReq_OledWriteString_msg
#define CoprocReq_OledSetCursor_fields &CoprocReq_OledSetCursor_msg
#define CoprocReq_OledDrawLine_fields &CoprocReq_OledDrawLine_msg
#define CoprocReq_OledDrawArc_fields &CoprocReq_OledDrawArc_msg
#define CoprocReq_OledDrawCircle_fields &CoprocReq_OledDrawCircle_msg
#define CoprocReq_OledDrawRectangle_fields &CoprocReq_OledDrawRectangle_msg
#define CoprocReq_MpuReq_fields &CoprocReq_MpuReq_msg
#define CoprocReq_EspWatchdogSettings_fields &CoprocReq_EspWatchdogSettings_msg
#define CoprocReq_CoprocStartupMessage_fields &CoprocReq_CoprocStartupMessage_msg
#define CoprocReq_SmartServoReq_fields &CoprocReq_SmartServoReq_msg
#define CoprocStat_fields &CoprocStat_msg
#define CoprocStat_ButtonsStat_fields &CoprocStat_ButtonsStat_msg
#define CoprocStat_UltrasoundStat_fields &CoprocStat_UltrasoundStat_msg
#define CoprocStat_MotorStat_fields &CoprocStat_MotorStat_msg
#define CoprocStat_PowerAdcStat_fields &CoprocStat_PowerAdcStat_msg
#define CoprocStat_VersionStat_fields &CoprocStat_VersionStat_msg
#define CoprocStat_RtcStat_fields &CoprocStat_RtcStat_msg
#define CoprocStat_FaultStat_fields &CoprocStat_FaultStat_msg
#define CoprocStat_MpuStat_fields &CoprocStat_MpuStat_msg
#define CoprocStat_MpuVector_fields &CoprocStat_MpuVector_msg
#define CoprocStat_SmartServoStat_fields &CoprocStat_SmartServoStat_msg

/* Maximum encoded size of messages (where known) */
#define CoprocReq_BuzzerReq_size                 2
#define CoprocReq_CalibratePower_size            24
#define CoprocReq_CoprocStartupMessage_size      10
#define CoprocReq_EspWatchdogSettings_size       2
#define CoprocReq_GetButtons_size                0
#define CoprocReq_I2cReq_size                    42
#define CoprocReq_MotorReq_SetPosition_size      12
#define CoprocReq_MotorReq_size                  27
#define CoprocReq_MpuReq_size                    6
#define CoprocReq_OledDrawArc_size               32
#define CoprocReq_OledDrawCircle_size            20
#define CoprocReq_OledDrawLine_size              26
#define CoprocReq_OledDrawPixel_size             14
#define CoprocReq_OledDrawRectangle_size         26
#define CoprocReq_OledInit_size                  16
#define CoprocReq_OledReq_size                   40
#define CoprocReq_OledSetCursor_size             12
#define CoprocReq_OledWriteString_size           38
#define CoprocReq_RtcReq_size                    6
#define CoprocReq_SetLeds_size                   2
#define CoprocReq_SetMotorCoupling_size          6
#define CoprocReq_SetStupidServo_size            11
#define CoprocReq_SmartServoReq_size             28
#define CoprocReq_UltrasoundReq_size             8
#define CoprocReq_size                           44
#define CoprocStat_ButtonsStat_size              2
#define CoprocStat_FaultStat_size                2
#define CoprocStat_MotorStat_size                26
#define CoprocStat_MpuStat_size                  76
#define CoprocStat_MpuVector_size                33
#define CoprocStat_PowerAdcStat_size             23
#define CoprocStat_RtcStat_size                  14
#define CoprocStat_SmartServoStat_size           26
#define CoprocStat_UltrasoundStat_size           12
#define CoprocStat_VersionStat_size              18
#define CoprocStat_size                          78
#define MotorConfig_size                         18
#define None_size                                0
#define RegCoefs_size                            18

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
